import pandas as pd

card_types = pd.DataFrame([['pink','train',False,1,7],
                            ['pink','train',True,1,4],
                            ['yellow','train',False,1,7],
                            ['yellow','train',True,1,4],
                            ['green','train',False,1,7],
                            ['green','train',True,1,4],
                            ['red','train',False,1,7],
                            ['red','train',True,1,4],
                            ['white','train',False,1,7],
                            ['white','train',True,1,4],
                            ['black','train',False,1,7],
                            ['black','train',True,1,4],
                            ['wild','train',False,1,14],
                            ['pink','ship',True,1,4],
                            ['pink','ship',False,2,6],
                            ['yellow','ship',True,1,4],
                            ['yellow','ship',False,2,6],
                            ['green','ship',True,1,4],
                            ['green','ship',False,2,6],
                            ['red','ship',True,1,4],
                            ['red','ship',False,2,6],
                            ['white','ship',True,1,4],
                            ['white','ship',False,2,6],
                            ['black','ship',True,1,4],
                            ['black','ship',False,2,6]],
                                columns = ['color','type','harbor','value','quantity'])